services:
  app:
    build: .
    ports:
      - "8000:5000"

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: issue_tracker
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: