"""added index on status field in Issue model

Revision ID: 16f62e8969c6
Revises: 6f5e9c9a543a
Create Date: 2026-06-22 00:14:59.590049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f62e8969c6'
down_revision: Union[str, Sequence[str], None] = '6f5e9c9a543a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_issues_table_status'), 'issues_table', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_table_status'), table_name='issues_table')
    # ### end Alembic commands ###
