"""just added a server side created time field stamp to the sqlalchemy schema

Revision ID: 6f5e9c9a543a
Revises: b72d16a11965
Create Date: 2026-06-21 18:36:59.196168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f5e9c9a543a'
down_revision: Union[str, Sequence[str], None] = 'b72d16a11965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components_table', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components_table', 'created_at')
    # ### end Alembic commands ###
